# Generated by Django 5.2.6 on 2025-09-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_registration_number',
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='business_barangay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='business_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='business_region',
            field=models.CharField(choices=[('ncr', 'National Capital Region (NCR)'), ('car', 'Cordillera Administrative Region (CAR)'), ('region1', 'Ilocos Region (Region I)'), ('region2', 'Cagayan Valley (Region II)'), ('region3', 'Central Luzon (Region III)'), ('region4a', 'CALABARZON (Region IV-A)'), ('region4b', 'MIMAROPA (Region IV-B)'), ('region5', 'Bicol Region (Region V)'), ('region6', 'Western Visayas (Region VI)'), ('region7', 'Central Visayas (Region VII)'), ('region8', 'Eastern Visayas (Region VIII)'), ('region9', 'Zamboanga Peninsula (Region IX)'), ('region10', 'Northern Mindanao (Region X)'), ('region11', 'Davao Region (Region XI)'), ('region12', 'SOCCSKSARGEN (Region XII)'), ('region13', 'Caraga (Region XIII)'), ('barmm', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)')], default='ncr', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='business_street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='company_tin',
            field=models.CharField(default='', help_text='Tax Identification Number', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='late_payment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Late payment fee (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lending_policy_description',
            field=models.TextField(blank=True, help_text='Brief description of loan approval process and criteria', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='loan_products_offered',
            field=models.JSONField(default=list, help_text='List of loan products offered'),
        ),
        migrations.AddField(
            model_name='company',
            name='loan_term_maximum_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='loan_term_minimum_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='maximum_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum interest rate (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='maximum_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='minimum_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum interest rate (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='minimum_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Processing fee (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sec_registration_number',
            field=models.CharField(default='', help_text='SEC Registration Number', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='years_in_operation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
