# Generated by Django 5.2.6 on 2025-09-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_company_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='company',
            name='verification_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='years_in_operation',
        ),
    ]
