# Generated by Django 5.2.6 on 2025-09-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_company_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='license_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
