# Generated by Django 5.2.6 on 2025-09-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_company_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='client',
            name='verification_date',
        ),
    ]
