# Generated by Django 5.2.6 on 2025-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_client_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='client',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='client',
            name='employer_name',
        ),
        migrations.AddField(
            model_name='client',
            name='bank_account_name',
            field=models.CharField(default='', help_text='Account holder name', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_account_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='current_barangay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='current_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='current_region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='current_street',
            field=models.CharField(default='', help_text='Building No., Street Name', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='permanent_barangay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='permanent_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='permanent_region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='permanent_street',
            field=models.CharField(default='', help_text='Building No., Street Name', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='source_of_income',
            field=models.TextField(blank=True, help_text='Brief description of income source', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
    ]
